### PR TITLE
Added dkms deb building into Makefile

### PR DESCRIPTION
**Pull request by CRImier**
I thought that it could streamline testing changes for those that don't yet know how to build DKMS packages. This is a straightforward way of doing it, copied from [this tutorial](http://www.xkyle.com/building-linux-packages-for-kernel-drivers/), so some steps might not be strictly necessary.

### CODE REVIEW

**Comment by CRImier** [comment]
One note: I haven't added anything into make clean, though it might be necessary to call dkms uninstall or dkms remove - I don't understand the process enough to know what has to be done for cleanup.

**Comment by al177** [comment]
I tried building this, but it fails in the mkdeb when copying the .deb from tmp to /var/lib/dkms.  I think this has to do with this Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832558 but I haven't been able to work around it so far without modifying the systemwide mkdeb template for dkms as in that bug report.

**Comment by CRImier** [comment]
Hmm, that's weird. But then, I did it on Raspbian Jessie, and it does have some config file changes compared to Debian. I think you should leave a comment in that bugtracker, mention that you're affected, maybe they take action quicker =) 

What was the process you used for building .deb packages before?

**Comment by al177** [comment]
The DKMS process you put in the Makefile is almost identical to the one I used by hand.  The DKMS source-only bug is a recent thing.

I updated the version# and pushed out a new DKMS deb release.

Thanks for fixing this!

**Comment by CRImier** [comment]
Happy to help! There are some more fixes in different forks, will see about merging them in the near future.

**Pull request merged**
