### PR TITLE
Merging: Fix compilation with newer kernels

### PR DESCRIPTION
**Pull request by CRImier**
I've stumbled upon the issue described in #16 , and decided to merge [the mentioned patch](https://github.com/jwrdegoede/esp8089/commit/865e748f060f4bcbefc0c16aa786e37551703bf3). I haven't yet tested it, but, at least, it builds correctly. So, don't yet merge it without testing the changes first - if I test  it before you do, I'll let you know.

### CODE REVIEW

**Comment by CRImier** [comment]
Installed and tested it - seems to work so far. Will keep you updated =)

**Comment by al177** [comment]
Thanks!  I'll test it out this weekend

**Comment by CRImier** [comment]
You might want to make a new .deb, then - and update the instructions on Hackaday.io! =)

**Comment by al177** [comment]
Done!  New release on the release page, and the HaD instructions reflect the new version.

**Pull request merged**
